---
# tasks file for bash-aliases
- name: add configuration directory
  file:
    dest: ~/bash_aliases.conf.d/
    state: directory

- name: add enabled aliases
  copy:
    src: "{{ item.src }}"
    dest: ~/bash_aliases.conf.d/
  when: "{{ item.enabled }}"
  with_items:
    - { src: docker.aliases, enabled: "{{ bash_aliases_docker|bool }}" }
    - { src: steam.aliases, enabled: "{{ bash_aliases_steam|bool }}" }

- name: remove disabled aliases
  file:
    dest: "~/bash_aliases.conf.d/{{ item.src }}"
    state: "{{ item.enabled | ternary('file', 'absent') }}"
  with_items:
    - { src: docker.aliases, enabled: "{{ bash_aliases_docker|bool }}" }
    - { src: steam.aliases, enabled: "{{ bash_aliases_steam|bool }}" }

- name: assemble .bash_aliases
  assemble:
    src: ~/bash_aliases.conf.d/
    dest: ~/.bash_aliases
    delimiter: "###"
...
